// Code generated by Icestudio 0.10-rc1

`default_nettype none

//---- Top entity
module main (
 input [1:0] vac0461,
 output [1:0] v763c80,
 output [0:5] vinit
);
 wire [0:1] w0;
 wire w1;
 wire w2;
 wire [0:1] w3;
 assign w0 = vac0461;
 assign v763c80 = w3;
 v0dbcb9 va52d1b (
  .v8b19dd(w0),
  .v3f8943(w1),
  .v64d863(w2)
 );
 v80ac84 v58d14b (
  .vee8a83(w1),
  .v03aaf0(w2),
  .v67a3fc(w3)
 );
 assign vinit = 6'b000000;
endmodule

//---- Top entity
module v0dbcb9 (
 input [1:0] v8b19dd,
 output v3f8943,
 output v64d863
);
 wire w0;
 wire w1;
 wire [0:1] w2;
 assign v3f8943 = w0;
 assign v64d863 = w1;
 assign w2 = v8b19dd;
 v0dbcb9_v9a2a06 v9a2a06 (
  .o1(w0),
  .o0(w1),
  .i(w2)
 );
endmodule

//---------------------------------------------------
//-- Bus2-Split-all
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus2-Split-all: Split the 2-bits bus into two wires
//---------------------------------------------------

module v0dbcb9_v9a2a06 (
 input [1:0] i,
 output o1,
 output o0
);
 assign o1 = i[1];
 assign o0 = i[0];
endmodule
//---- Top entity
module v80ac84 (
 input vee8a83,
 input v03aaf0,
 output [1:0] v67a3fc
);
 wire w0;
 wire w1;
 wire [0:1] w2;
 assign w0 = vee8a83;
 assign w1 = v03aaf0;
 assign v67a3fc = w2;
 v80ac84_v9a2a06 v9a2a06 (
  .i1(w0),
  .i0(w1),
  .o(w2)
 );
endmodule

//---------------------------------------------------
//-- Bus2-Join-all
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus2-Join-all: Joint two wires into a 2-bits Bus
//---------------------------------------------------

module v80ac84_v9a2a06 (
 input i1,
 input i0,
 output [1:0] o
);
 assign o = {i1, i0};
 
endmodule
